### ISSUE TITLE
오류 http://gapm.io/dl_pop

### ISSUE THREAD

**Issue by worldinyj** [jongheepark/BayesianSocialScience#1]
안녕하세요. 
교수님책을 구입해서 스터디를 하고 있는 1인입니다.
파일 다운로드가 안되고 갭마인더 홈페이지에서도 다운되는 자료가 책에서 사용하는 것과 다릅니다.
혹시 해당 엑셀파일을 따로 올려주실 수 없을까요?

**Comment by jongheepark** [comment]
어떤 자료를 말씀하시는 거죠? 
인구자료인가요? 

박종희 드림

**Comment by worldinyj** [comment]
답변 메일 및 깃허브 자료업데이트 감사드립니다.
